import type { SecretGenerator } from "../application/ports";
import type { Password } from "../domain/credentials";
import { INVITE_ALPHABET, type InviteCode } from "../domain/invite";

// Words for temporary passwords: easy to read aloud and type. 128 words, so each word is one
// of 2^7 choices; four words give 2^28 possibilities. That is plenty for a password that is
// used once, on a home server, and must be changed straight away.
const WORDS = [
  "angel",
  "anvil",
  "arrow",
  "ash",
  "aura",
  "badger",
  "banner",
  "basilisk",
  "beacon",
  "bear",
  "blade",
  "bloom",
  "bog",
  "bolt",
  "bone",
  "bramble",
  "brass",
  "bridge",
  "brook",
  "candle",
  "canyon",
  "castle",
  "cave",
  "cedar",
  "chain",
  "chalice",
  "cinder",
  "claw",
  "cliff",
  "cloak",
  "cloud",
  "comet",
  "coral",
  "crown",
  "crystal",
  "dagger",
  "dawn",
  "delta",
  "dragon",
  "drake",
  "dune",
  "dusk",
  "eagle",
  "echo",
  "elf",
  "elk",
  "ember",
  "falcon",
  "fang",
  "fern",
  "fire",
  "flame",
  "forest",
  "forge",
  "fox",
  "frost",
  "gale",
  "garden",
  "gem",
  "giant",
  "glade",
  "goblin",
  "golem",
  "griffin",
  "grove",
  "harbor",
  "hawk",
  "hearth",
  "helm",
  "heron",
  "hill",
  "horn",
  "hydra",
  "ice",
  "island",
  "ivy",
  "jade",
  "kraken",
  "lantern",
  "lotus",
  "lynx",
  "mage",
  "maple",
  "marsh",
  "meadow",
  "mesa",
  "mist",
  "moon",
  "moss",
  "mountain",
  "oak",
  "ocean",
  "onyx",
  "orb",
  "otter",
  "owl",
  "pearl",
  "phoenix",
  "pine",
  "plains",
  "quartz",
  "raven",
  "reef",
  "relic",
  "ridge",
  "river",
  "rune",
  "sage",
  "scroll",
  "shade",
  "shield",
  "shore",
  "sky",
  "slate",
  "sphinx",
  "spire",
  "sprite",
  "star",
  "stone",
  "storm",
  "swamp",
  "sword",
  "thorn",
  "tide",
  "titan",
  "tower",
  "wolf",
  "wyrm",
];

/** Uniform random integers in [0, size) from the operating system's secure random source. */
function secureRandomIndexes(count: number, size: number): number[] {
  // `size` is a power of two (32 or 128), so `value % size` is perfectly uniform.
  const values = crypto.getRandomValues(new Uint32Array(count));
  return Array.from(values, (value) => value % size);
}

export function cryptoSecretGenerator(): SecretGenerator {
  return {
    inviteCode() {
      const characters = secureRandomIndexes(12, INVITE_ALPHABET.length).map(
        (index) => INVITE_ALPHABET[index],
      );
      const groups = [characters.slice(0, 4), characters.slice(4, 8), characters.slice(8, 12)];
      return groups.map((group) => group.join("")).join("-") as InviteCode;
    },

    temporaryPassword() {
      const words = secureRandomIndexes(4, WORDS.length).map((index) => WORDS[index]);
      return words.join("-") as Password;
    },
  };
}
